name: cronotest
description: App para gravaÃ§Ã£o de vÃ­deos e fotos automÃ¡ticas
publish_to: 'Diego Nessler'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ“· Funcionalidades do app
  camera: ^0.11.2
  path_provider: ^2.1.1
  video_player: ^2.7.2
  image: ^4.1.3
  table_calendar: ^3.1.2
  permission_handler: ^12.0.1
  screen_capture_event: ^1.2.0

  # ğŸ¨ UI e Ã­cones
  cupertino_icons: ^1.0.8

  # ğŸ§  Gerenciamento de estado
  provider: ^6.0.5

  # ğŸ’¾ PersistÃªncia
  shared_preferences: ^2.2.2

  # ğŸŒ InternacionalizaÃ§Ã£o
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_app.png
    - assets/icon.png
  generate: true